language: node_js
node_js:
  - "0.12.15"
  - "4.4.4"
  - "5.11.0"
  - "6.3.0"
env:
  - EXPORT_COVERAGE=1 CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
branches:
  only:
    - master
